interface EventoObjeto {
      tipoEvento: string,
      statusEvento: string,
      descricaoEvento: string,
      nomeUnidade: string,
      municipio: string,
      uf: string,
      dataCriacao: string,
      latitude: string,
      longitude: string,
      nomeRemetente: string,
      cepRemetente: string,
      logradouroRemetente: string,
      complementoRemetente: string,
      numeroRemetente: string,
      bairroRemetente: string,
      cidadeRemetente: string,
      ufRemetente: string,
      paisRemetente: string,
      nomeDestinatario: string,
      cepDestinatario: string,
      logradouroDestinatario: string,
      complementoDestinatario: string,
      emailDestinatario: string,
      numeroDestinatario: string,
      bairroDestinatario: string,
      cidadeDestinatario: string,
      ufDestinatario: string,
      paisDestinatario: string,
      nomeRecebedor: string,
      dataRecebimento: string,
      documento: string,
      matricula: string,
      usuario: string,
      codigoSRO: string,
}

interface Objeto {
  codigo: string,
  imagemBase64: string,
  mensagem: string,
  eventos: EventoObjeto[],
  tipo: string,
  tipoEventoImagem: string,
  dataCriacaoImagem: string,
  statusEventoImagem: string,
}
